---
abstract: 'Perl interface to the Keccak digest algorithm'
author:
  - 'gray <gray@cpan.org>'
build_requires:
  Test::More: 0.82
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Digest-Keccak
no_index:
  directory:
    - t
    - inc
requires:
  Digest: 0
  parent: 0
resources:
  repository: http://github.com/gray/digest-keccak
version: 0.05
